#!/bin/sh
set -e

#DEBHELPER#

cd /usr/lib/
if [ ! -d indieauth-client-php ];
then
    mkdir indieauth-client-php
fi
cd indieauth-client-php || exit 2
composer require indieauth/client

cd /usr/src/mindie-client/
touch indieauth-client-php/.htaccess
chgrp www-data indieauth-client-php/.htaccess
chmod u+r-wx,g+rw-x,o-rwx indieauth-client-php/.htaccess

/usr/bin/new-mindie-client /var/lib/indieauth-client/ > /dev/null

exit 0
